import { LocationId } from "../types.js";

export const locations: readonly LocationId[] = Object.freeze([
    "gallia_cisalpina",
    "gallia-gallia_cisalpina",
    "gallia",
    "dalmatia-gallia_cisalpina",
    "dalmatia",
    "dalmatia-macedonia",
    "macedonia",
    "macedonia-achaia",
    "achaia",
    "achaia-creta",
    "achaia-africa",
    "creta",
    "creta-asia",
    "asia",
    "asia-syria",
    "syria",
    "aegyptus-syria",
    "aegyptus",
    "gallia_cisalpina-italia",
    "gallia-hispania_citerior",
    "hispania_citerior",
    "hispania_citerior-hispania_ulterior",
    "hispania_ulterior",
    "hispania_ulterior-mauritania",
    "mauritania",
    "sardinia-mauritania",
    "mauritania-numidia",
    "numidia",
    "sicilia-numidia",
    "sicilia",
    "sicilia-sardinia",
    "sardinia",
    "gallia-sardinia",
    "sardinia-italia",
    "sicilia-italia",
    "sicilia-africa",
    "numidia-africa",
    "italia",
    "italia_bonus",
    "italia-dalmatia",
    "italia-macedonia",
    "italia-achaia",
    "aegyptus-asia",
    "creta-aegyptus",
    "creta-cyrene",
    "africa-cyrene",
    "africa",
    "cyrene",
    "cyrene-aegyptus",
]);

export const provincesBarringItalia: readonly LocationId[] = Object.freeze([
    "gallia_cisalpina",
    "gallia",
    "dalmatia",
    "macedonia",
    "achaia",
    "creta",
    "asia",
    "syria",
    "aegyptus",
    "hispania_citerior",
    "hispania_ulterior",
    "mauritania",
    "numidia",
    "sicilia",
    "sardinia",
    "africa",
    "cyrene",
]);

export const provinces: readonly LocationId[] = Object.freeze([
    "gallia_cisalpina",
    "gallia",
    "dalmatia",
    "macedonia",
    "achaia",
    "creta",
    "asia",
    "syria",
    "aegyptus",
    "hispania_citerior",
    "hispania_ulterior",
    "mauritania",
    "numidia",
    "sicilia",
    "sardinia",
    "africa",
    "cyrene",
    "italia",
]);

export const provinceBordersDictionary: Record<LocationId, LocationId[]> =
    Object.freeze({
        gallia_cisalpina: [
            "dalmatia-gallia_cisalpina",
            "gallia_cisalpina-italia",
            "gallia-gallia_cisalpina",
        ],
        dalmatia: [
            "dalmatia-gallia_cisalpina",
            "italia-dalmatia",
            "dalmatia-macedonia",
        ],
        gallia: [
            "gallia-gallia_cisalpina",
            "gallia-sardinia",
            "gallia-hispania_citerior",
        ],
        macedonia: [
            "dalmatia-macedonia",
            "italia-macedonia",
            "macedonia-achaia",
        ],
        achaia: [
            "macedonia-achaia",
            "achaia-creta",
            "achaia-africa",
            "italia-achaia",
        ],
        creta: ["creta-asia", "creta-aegyptus", "creta-cyrene", "achaia-creta"],
        asia: ["creta-asia", "aegyptus-asia", "asia-syria"],
        syria: ["aegyptus-syria", "asia-syria"],
        aegyptus: [
            "aegyptus-syria",
            "aegyptus-asia",
            "creta-aegyptus",
            "cyrene-aegyptus",
        ],
        hispania_citerior: [
            "gallia-hispania_citerior",
            "hispania_citerior-hispania_ulterior",
        ],
        hispania_ulterior: [
            "hispania_ulterior-mauritania",
            "hispania_citerior-hispania_ulterior",
        ],
        mauritania: [
            "hispania_ulterior-mauritania",
            "sardinia-mauritania",
            "mauritania-numidia",
        ],
        numidia: ["numidia-africa", "sicilia-numidia", "mauritania-numidia"],
        sicilia: [
            "sicilia-africa",
            "sicilia-italia",
            "sicilia-sardinia",
            "sicilia-numidia",
        ],
        sardinia: [
            "sardinia-mauritania",
            "sicilia-sardinia",
            "sardinia-italia",
            "gallia-sardinia",
        ],
        africa: [
            "africa-cyrene",
            "numidia-africa",
            "sicilia-africa",
            "achaia-africa",
        ],
        cyrene: ["africa-cyrene", "creta-cyrene", "cyrene-aegyptus"],
        italia: [
            "gallia_cisalpina-italia",
            "italia-dalmatia",
            "italia-macedonia",
            "italia-achaia",
            "sicilia-italia",
            "sardinia-italia",
        ],
    });

export const borderProvincesDictionary: Record<LocationId, LocationId[]> =
    Object.freeze({
        "dalmatia-gallia_cisalpina": ["gallia_cisalpina", "dalmatia"],
        "gallia_cisalpina-italia": ["gallia_cisalpina", "italia"],
        "gallia-gallia_cisalpina": ["gallia_cisalpina", "gallia"],
        "italia-dalmatia": ["dalmatia", "italia"],
        "dalmatia-macedonia": ["dalmatia", "macedonia"],
        "gallia-sardinia": ["gallia", "sardinia"],
        "gallia-hispania_citerior": ["gallia", "hispania_citerior"],
        "italia-macedonia": ["macedonia", "italia"],
        "macedonia-achaia": ["macedonia", "achaia"],
        "achaia-creta": ["achaia", "creta"],
        "achaia-africa": ["achaia", "africa"],
        "italia-achaia": ["achaia", "italia"],
        "creta-asia": ["creta", "asia"],
        "creta-aegyptus": ["creta", "aegyptus"],
        "creta-cyrene": ["creta", "cyrene"],
        "aegyptus-asia": ["asia", "aegyptus"],
        "asia-syria": ["asia", "syria"],
        "aegyptus-syria": ["syria", "aegyptus"],
        "cyrene-aegyptus": ["aegyptus", "cyrene"],
        "hispania_citerior-hispania_ulterior": [
            "hispania_citerior",
            "hispania_ulterior",
        ],
        "hispania_ulterior-mauritania": ["hispania_ulterior", "mauritania"],
        "sardinia-mauritania": ["mauritania", "sardinia"],
        "mauritania-numidia": ["mauritania", "numidia"],
        "numidia-africa": ["numidia", "africa"],
        "sicilia-numidia": ["numidia", "sicilia"],
        "sicilia-africa": ["sicilia", "africa"],
        "sicilia-italia": ["sicilia", "italia"],
        "sicilia-sardinia": ["sicilia", "sardinia"],
        "sardinia-italia": ["sardinia", "italia"],
        "africa-cyrene": ["africa", "cyrene"],
    });
